openapi: 3.0.0
info:
  version: 1.0.0
  title: Users API
  description: This is a sample OpenAPI definition for a Users API..
  contact:
    name: Kevin Swiber
    email: kswiber@gmail.com
  license:
    name: Apache/2
servers:
  - url: 'https://reqres.in/api'
tags:
  - name: users
    description: User management operations.
paths:
  /users2:
    get:
      summary: List Users
      description: Returns a full list of users.
      operationId: listUsers
      tags:
        - users
      responses:
        '200':
          description: A list of users.
          content:
           application/json:
              schema:
                $ref: '#/components/schemas/ListUsersResponse'
  '/users/{userId}':
    parameters:
      - schema:
          type: integer
          format: int64
        name: userId
        in: path
        required: true
        description: The ID of the user.
        example: 12345
    get:
      summary: Get a Single User
      description: Returns a single user.
      operationId: getUser
      tags:
        - users
      responses:
        '200':
          description: A single user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserResponse'
components:
  schemas:
    User:
      type: object
      required:
        - id
        - email
        - first_name
        - last_name
        - avatar
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
        first_name:
          type: string
        avatar:
          type: string
      example:
        id: 12345
        email: blah@example.com
        first_name: George
        last_name: Burns
        avatar: https://george.burns/avatar
    GetUserResponse:
      title: GetUserResponse
      type: object
      properties:
        data:
          type: object
          $ref: '#/components/schemas/User'
      example:
        data:
          id: 12345
          email: blah@example.com
          first_name: George
          last_name: Burns
          avatar: https://george.burns/avatar    
    ListUsersResponse:
      title: ListUsersResponse
      type: object
      properties:
        per_page:
          type: integer
          format: int32
        total:
          type: integer
          format: int32
        total_pages:
          type: integer
          format: int32
        data:
          type: array
          items:
            $ref: '#/components/schemas/User'
      example:
        page: 1
        per_page: 10
        total: 30
        total_pages: 3
        data:
          - id: 12345
            email: blah@example.com
            first_name: George
            last_name: Burns
            avatar: https://george.burns/avatar

